### ISSUE TITLE
[Bug]: SVG files cannot be used as images

### ISSUE THREAD

**Issue by individual-it** [JankariTech/web-app-presentation-viewer#85]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Describe the bug

PNG files work fine, but not SVG

### Steps To Reproduce

create an presentation with an image like
`![image](./somefile.svg)`

### Expected Behavior

image is shown

### Actual Behavior

image is not loaded

### Environment

- **OS**: Ubuntu 22.04
- **ownCloud Web**: ownCloud Web UI 10.2.0
- **oCIS**: Infinite Scale 6.4.0

### What browsers are you seeing the problem on?

Firefox

**Comment by saw-jan** [comment]
ocis-web doesn't support `.svg` file to be opened by image viewer. That's why the extension is also not building the required url for .svg files. It's because the svg mimetype is not included in the mimetypes list.

We should be able to fix it for the extension by just adding the required svg mimetype.
